# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_core.ipynb 1
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
say_hello("Sushil")

# %% ../nbs/00_core.ipynb 3
from IPython.display import display,SVG
display(SVG('<svg height="100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="40"/></svg>'))
def foo(): pass
